config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    resources :ideas
  end

  namespace :admin do
    resources :categories, only: ['index']
    resources :images, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :ideas
  validates :name, presence: true, uniqueness: true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :category
  belongs_to :user
  validates :title, presence: true, uniqueness:true
  validates :description, presence: true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :ideas
  validates :username, presence: true , uniqueness: true
  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||=User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_user, only: [:index, :new, :create, :destroy]

  def index
    @user = current_user
    @ideas = Idea.all
  end

  def new
    @categories = Category.all
    @user = current_user
    @idea = Idea.new()
  end

  def create
    @categories = Category.all
    @user = current_user
    @idea = @user.ideas.new(idea_params)
    if @idea.save
      flash[:success] = "#{@idea.title} added"
      redirect_to user_ideas_path(@user)
    else
      render :new
    end
  end

  def edit
    @categories = Category.all
    @user = current_user
    @idea = Idea.find(params[:id])
  end

  def update
    @categories = Category.all
    @user = current_user
    @idea = Idea.find(params[:id])
    @idea.update(idea_params)
    if @idea.save
      flash[:success] = "#{@idea.title} updated!"
      redirect_to user_ideas_path(@user)
    else
      render :edit
    end
  end

  def show
    @user = current_user
    @ideas = Idea.find(params[:id])
  end

  def destroy
    @user = current_user
    @idea = Idea.find(params[:id])
    @idea.destroy

    flash[:success] = "#{@idea.title} was successfully deleted!"
    redirect_to user_ideas_path(@user)
  end

  private

  def set_user
    @user = current_user
  end

  def idea_params
    params.require(:idea).permit(:title, :description, :category_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      #either user doesn't exist or password is incorrect
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      #re render new view if validations don't pass
    end
  end

  def show
    @user = current_user
  end
  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/index.html.erb
<h1>Admin Categories</h1>

<% @categories.each do |category| %>
<%= category.name %>
<% end %>

app/views/ideas/edit.html.erb
<h1>Edit and Idea!</h1>
<%= form_for [@user, @idea] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :category %>
  <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %><br>
  <%= f.submit "Edit Idea" %>
<% end %>

app/views/ideas/index.html.erb
<h1>All Ideas</h1>
<div>
<% @ideas.each do |idea| %>
<h3><%= idea.title %></h3>
<%= idea.description %><br>
<%= link_to "Delete", user_idea_path(@user, idea), method: "delete" %>
<% end %>
</div>

<%= link_to "Create New Idea", new_user_idea_path %>

app/views/ideas/new.html.erb
<h1>Create a New Idea!</h1>
<%= form_for [@user, @idea] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :description %>
  <%= f.text_field :description %><br>
  <%= f.label :category %>
  <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %><br>
  <%= f.submit "Create Idea" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeasBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      Welcome <%= current_user.username  %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Create an Account</h1>
<%= form_for(@user) do |f| %>
<%= f.label :username %>
<%= f.text_field :username %><br>

<%= f.label :password %>
<%= f.text_field :password %><br>
<%= f.submit "Create Account" %>
<% end %>

<%= link_to "User Login", login_path %>

app/views/users/show.html.erb
<h1>See the USER!</h1>

<%= link_to "Create an Idea", new_user_idea_path(@user)  %>